name: kohya-docker

services:
  kohya-ss-gui:
    container_name: kohya-ss-gui
    image: ghcr.io/bmaltais/kohya-ss-gui:latest
    user: "${UID:-1000}:0"
    build:
      context: .
      network: host
      args:
        - UID=${UID:-1000}
      cache_from:
        - ghcr.io/bmaltais/kohya-ss-gui:cache
      cache_to:
        - type=inline
    ports:
      - "127.0.0.1:${KOHYA_PORT:-7861}:7860"
    environment:
      SAFETENSORS_FAST_GPU: 1
      TENSORBOARD_PORT: ${TENSORBOARD_PORT:-6006}
    tmpfs:
      - /tmp
    volumes:
      - ${MODELS_HOST_PATH:-./models}:/app/models
      - ./presets:/app/presets
      - ./dataset:/dataset
      - ./dataset:/app/data
      - ./dataset/logs:/app/logs
      - ./dataset/outputs:/app/outputs
      - ./dataset/regularization:/app/regularization
      - ./.cache/config:/app/config
      - ./.cache/user:/home/1000/.cache
      - ./.cache/triton:/home/1000/.triton
      - ./.cache/nv:/home/1000/.nv
      - ./.cache/keras:/home/1000/.keras
      - ./.cache/config:/home/1000/.config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]

  tensorboard:
    container_name: kohya-tensorboard
    image: tensorflow/tensorflow:latest
    profiles: ["tensorboard"]
    ports:
      - "127.0.0.1:${TENSORBOARD_PORT:-6006}:6006"
    volumes:
      - ./dataset/logs:/app/logs
    command: tensorboard --logdir=/app/logs --bind_all
